version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: epsilon_db
      POSTGRES_USER: epsilon_user
      POSTGRES_PASSWORD: epsilon_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - springboot-network

  app:
    build: .
    container_name: springboot_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/epsilon
    ports:
      - "8080:8080"
    networks:
      - springboot-network

volumes:
  postgres_data:

networks:
  springboot-network:
